### ISSUE TITLE
启动报错

### ISSUE THREAD

**Issue by stzhongjie** [lquan529/vue-city-picker#1]
npm run dev启动项目时node报错：

Error: listen EADDRNOTAVAIL 192.168.1.175:8080

应该是config/index.js里设置了host: '192.168.1.175'

**Comment by lquan529** [comment]
哦，不好意思，这个我调试的时候忘记改回去了
你找到 config/index.js
host: 'localhost', // can be overwritten by process.env.HOST
修改回 localhost 就可以了
